# Generated by Django 5.2.4 on 2025-08-07 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vtu', '0002_transaction_customer_name_transaction_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='created_at',
            new_name='date',
        ),
    ]
