# Generated by Django 5.2.4 on 2025-08-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtu', '0003_rename_created_at_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='external_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='raw_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('request_id',)},
        ),
    ]
