# Generated by Django 5.2.4 on 2025-08-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vtu', '0007_delete_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('MTN', 'MTN'), ('GLO', 'GLO'), ('AIRTEL', 'Airtel'), ('9MOBILE', '9mobile')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('variation_code', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
