# Generated by Django 5.2.4 on 2025-08-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtu', '0008_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataplan',
            old_name='price',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='dataplan',
            old_name='name',
            new_name='plan_name',
        ),
        migrations.RenameField(
            model_name='dataplan',
            old_name='variation_code',
            new_name='volume',
        ),
        migrations.AddField(
            model_name='dataplan',
            name='plan_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='dataplan',
            name='validity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dataplan',
            name='network',
            field=models.CharField(choices=[('MTN', 'MTN'), ('GLO', 'GLO'), ('AIRTEL', 'AIRTEL'), ('9MOBILE', '9mobile')], max_length=20),
        ),
    ]
