# Generated by Django 5.2.4 on 2025-08-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtu', '0009_rename_price_dataplan_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('DSTV', 'DSTV'), ('GOTV', 'GOTV'), ('STARTIMES', 'Startimes')], max_length=20)),
                ('plan_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_code', models.CharField(max_length=50)),
            ],
        ),
    ]
