# Generated by Django 5.2.4 on 2025-08-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtu', '0010_tvplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvplan',
            name='validity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
