"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import environ
from decouple import config
import dj_database_url



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

DEBUG = os.environ.get('DEBUG', "True") == "True"
SECRET_KEY = os.environ.get('SECRET_KEY', "dev-secret")

ALLOWED_HOSTS = os.environ.get(
    "ALLOWED_HOSTS",
    "localhost,127.0.0.1,.onrender.com,.up.railway.app,websubapp.name.ng,www.websubapp.name.ng,my-web-app-wjj4.onrender.com"
).split(",")

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
SECURE_SSL_DIRECT = False

#============ CUSTOM KEYS ===================#
    #-------- PAYSTACK KEYS -----------------#
PAYSTACK_PUBLIC_KEY = env("PAYSTACK_PUBLIC_KEY")
PAYSTACK_SECRET_KEY = env('PAYSTACK_SECRET_KEY')
PAYSTACK_BASE_URL = env('PAYSTACK_BASE_URL')
PAYSTACK_CALLBACK_URL = env('PAYSTACK_CALLBACK_URL')
PAYSTACK_WEBHOOK_URL=env('PAYSTACK_WEBHOOK_URL')

PAYSTACK_PUBLIC_TEST_KEY=env('PAYSTACK_PUBLIC_TEST_KEY')
PAYSTACK_SECRET_TEST_KEY='sk_test_4370a09912654ae8b23f107a83841a9df112d48a4'

PREFERRED_BANK_SLUG='wema-bank'
COUNTRY_CODE='NG'

#-------------- LOGGING -------------------------#
LOGS_DIR = BASE_DIR / "logs"
LOGS_DIR.mkdir(exist_ok=True)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} [{name}:{lineno}] {modeule} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'wallet_file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': LOGS_DIR / 'wallet_log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'wallet': {
            'handlers': ['wallet_file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

    #--------- MONNIFY KEYS -----------------#
MONNIFY_API_KEY = env("MONNIFY_API_KEY")
MONNIFY_SECRET_KEY = env('MONNIFY_SECRET_KEY')
MONNIFY_CONTRACT_CODE = env('MONNIFY_CONTRACT_CODE')
MONNIFY_BASE_URL = 'https://api.monnify.com'
PREFERRED_BANK='WEMA_BANK'
COUNTRY_CODE='NG'
MONNIFY_WEBHOOK_URL='https://118ffa82ab5d.ngrok-free.app/wallet/webhook/monnify/'
MONNIFY_CALLBACK_URL='https://118ffa82ab5d.ngrok-free.app/wallet/fund/callback/'

    #-------- ACCOUNT DETAILS ---------------#
BANK_NAME = env('BANK_NAME')
ACCOUNT_NAME = env('ACCOUNT_NAME')
ACCOUNT_NUMBER = env('ACCOUNT_NUMBER')

#------- VTPASS --------#
VT_PASS_BASE = env('VTPASS_BASE', default='https://vtpass.com/api')
# VT_PASS_API_KEY = env('VT_PASS_API_KEY')
VTPASS_PUBLIC_KEY = env('VTPASS_PUBLIC_KEY')
VTPASS_SECRET = env('VTPASS_SCRET', default='')
VTPASS_SANDBOX = env.bool('VTPASS_SANDBOX', default=True)
VTPASS_USERNAME= env('VTPASS_USERNAME')
VTPASS_PASSWORD= env('VTPASS_PASSWORD')

#=============================================#

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=rzp(cro+e3a#mk9(dmmh+)fbb=j4uomikoi_40=r5*2g=f0)q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    # 'Fund_wallet'
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Custom Apps
    'base',
    'register',
    'wallet',
    'vtu',
]

MIDDLEWARE = [
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(default=f"sqlite:///{BASE_DIR}/db.sqlite3", conn_max_age=600, ssl_require=True)
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

CSRF_TRUSTED_ORIGINS = [
    "https://my-web-app-wjj4.onrender.com",
    "https://websubapp.name.ng",
    "https://www.websubapp.name.ng",
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# AUTH_USER_MODEL = 'register.UserProfile'

JAZZMIN_SETTINGS = {
    'site_header': 'WebSubApp',
    'site_brand': 'Subscription App',
    'site_logo': "images/logo.png",
}
