# Generated by Django 5.2.4 on 2025-08-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_userprofile_currency_fundingtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='paystack_customer_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='virtual_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='virtual_account_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='virtual_bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='FundingTransaction',
        ),
    ]
