# Generated by Django 5.2.4 on 2025-08-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_userprofile_paystack_customer_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='paystack_customer_code',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='monnify_account_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='virtual_account_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigning', 'Assigning'), ('active', 'Active'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
