# Generated by Django 5.2.4 on 2025-08-16 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_remove_userprofile_paystack_customer_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='monnify_account_reference',
            new_name='paystack_account_reference',
        ),
    ]
