# Generated by Django 5.2.4 on 2025-08-16 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_rename_monnify_account_reference_userprofile_paystack_account_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='paystack_account_reference',
            new_name='paystack_customer_code',
        ),
    ]
