# Generated by Django 5.2.4 on 2025-08-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_rename_paystack_account_reference_userprofile_paystack_customer_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='virtual_account_number',
            new_name='account_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='virtual_account_status',
            new_name='account_status',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='virtual_bank_name',
            new_name='bank_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
