# Generated by Django 5.2.4 on 2025-08-19 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_rename_virtual_account_number_userprofile_account_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='account_name',
            new_name='virtual_account_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='account_number',
            new_name='virtual_account_number',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='account_status',
            new_name='virtual_account_status',
        ),
    ]
