# Generated by Django 5.2.4 on 2025-08-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_rename_account_name_userprofile_virtual_account_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='bank_name',
            new_name='virtual_bank_name',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='virtual_account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='virtual_account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='virtual_account_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigning', 'Assigning'), ('active', 'Active'), ('failed', 'Failed')], default='pending', max_length=100),
        ),
    ]
