# Generated by Django 5.2.4 on 2025-08-22 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_rename_bank_name_userprofile_virtual_bank_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='virtual_bank_name',
            new_name='virtual_account_bank',
        ),
    ]
