# Generated by Django 5.2.4 on 2025-08-23 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_alter_userprofile_referral_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='paystack_customer_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='virtual_account_bank',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='virtual_account_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='virtual_account_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='virtual_account_status',
        ),
        migrations.CreateModel(
            name='DedicatedVirtualAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=15, unique=True)),
                ('account_name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
