# Generated by Django 5.2.4 on 2025-08-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_remove_userprofile_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='paystack_customer_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='virtual_account_bank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='virtual_account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='virtual_account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='virtual_account_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigning', 'Assigning'), ('active', 'Active'), ('failed', 'Failed')], default='pending', max_length=100),
        ),
        migrations.DeleteModel(
            name='DedicatedVirtualAccount',
        ),
    ]
