# Generated by Django 5.2.4 on 2025-08-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_userprofile_paystack_customer_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(default='NGN', max_length=3),
        ),
    ]
