# Generated by Django 5.2.4 on 2025-08-15 05:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingtransaction',
            name='reference',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
