# Generated by Django 5.2.4 on 2025-08-17 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_rename_fundingtransaction_walletfunding_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
