# Generated by Django 5.2.4 on 2025-08-18 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='customer_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
