# Generated by Django 5.2.4 on 2025-08-19 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_wallet_wallet_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='paystack_customer_code',
            new_name='monnify_customer_code',
        ),
    ]
