# Generated by Django 5.2.4 on 2025-08-22 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_remove_walletfunding_user_fundingtransaction_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FundingTransaction',
        ),
    ]
