# Generated by Django 5.2.4 on 2025-08-17 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=20)),
                ('provider', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone', models.CharField(max_length=15)),
                ('smartcard_number', models.CharField(blank=True, max_length=30, null=True)),
                ('meter_number', models.CharField(blank=True, max_length=30, null=True)),
                ('variation_code', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('request_id', models.CharField(max_length=100)),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('external_status', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('transaction_type', models.CharField(choices=[('airtime', 'Airtime Purchase'), ('data', 'Data Purcase'), ('wallet_fund', 'Wallet Funding'), ('quick_transfer', 'Quick Transfer'), ('electricity', 'Electricity'), ('tv', 'TV Subscription')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vtu_transaction', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('request_id',)},
            },
        ),
    ]
