# Generated by Django 5.2.4 on 2025-08-18 15:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_transaction_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('user', 'reference')},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='request_id',
        ),
    ]
