# Generated by Django 5.2.4 on 2025-08-18 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_transaction_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('reference',)},
        ),
    ]
