# Generated by Django 5.2.4 on 2025-08-18 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_transaction_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set(),
        ),
    ]
