# Generated by Django 5.2.4 on 2025-08-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_transaction_fee_amount_transaction_gross_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cashback',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='account_number',
            field=models.CharField(max_length=20),
        ),
    ]
