# Generated by Django 5.2.4 on 2025-08-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_transaction_cashback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='meter_type',
            field=models.CharField(default='prepaid', max_length=20),
        ),
    ]
