# Generated by Django 5.2.4 on 2025-08-22 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_transaction_bank_name_transaction_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='bank_name',
            new_name='virtual_bank_name',
        ),
    ]
