# Generated by Django 5.2.4 on 2025-08-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_bank_name_transaction_virtual_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='virtual_account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='virtual_account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='virtual_account_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigning', 'Assigning'), ('active', 'Active'), ('failed', 'Failed')], default='pending', max_length=100),
        ),
    ]
