# Generated by Django 5.2.4 on 2025-08-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_transaction_virtual_account_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='paystack_customer_code',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='virtual_account_name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='virtual_account_number',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='virtual_account_status',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='virtual_bank_name',
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
