# Generated by Django 5.2.4 on 2025-08-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_transaction_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='meter_type',
            field=models.CharField(choices=[('prepaid', 'Prepaid'), ('postpaid', 'Postpaid')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='provider',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
