# Generated by Django 5.2.4 on 2025-08-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_transaction_meter_type_alter_transaction_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='method',
            field=models.CharField(choices=[('dva', 'DVA'), ('inline', 'Inline')], default='dva', max_length=20),
        ),
    ]
