# Generated by Django 5.2.4 on 2025-08-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_transaction_final_amount_transaction_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='initial_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
