# Generated by Django 5.2.4 on 2025-08-30 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_transaction_initial_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='provider',
            field=models.CharField(choices=[('MTN', 'MTN'), ('GLO', 'GLO'), ('AIRTEL', 'Airtel'), ('9MOBILE', '9Mobile'), ('DSTV', 'DSTV'), ('GOTV', 'GOTV'), ('STARTIMES', 'Startimes'), ('IKEDC', 'IKEDC'), ('EKEDC', 'EKEDC'), ('AEDC', 'AEDC'), ('KADUNA', 'Kaduna'), ('IBEDC', 'IBEDC'), ('JOS', 'Jos')], max_length=30),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to=settings.AUTH_USER_MODEL),
        ),
    ]
